version = 1

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "java"
enabled = true

[[transformers]]
name = "google-java-format"
enabled = true