language: java
jdk:
  - oraclejdk11

addons:
  sonarcloud:
    organization: "robbinespu"
    token:
      secure: "yGnSp57Otn9sXlG4hQTIUyKRc7+LTotmCJ2fe8fevBcCcnkhu875iQcUmxPkFQA6/IMoFQEwfHC4t0Tt8tbxXLfzaJzeQR9QUhEAUO+4luwflDHLpNanuGJJfffHTzXb01xs5Q17Y2NxoH2TBdNKRGWFuyO78YYMogiUzDPY+VfqL/J1y1oP/cr9Zrv6GK4ASnmXpa159TYOO3v3LXk08IbS1YWeauGm/MVWSbgefcA9w4TQhUwadXT6Nf367NDAjMpvcqk8ZHcoUAc+BSznXhJYN8AH5wVUAbmZmbPBxWpOvkLDCjToyOGjWWDXNs/TL+KOCVg51Soqm+dGUJK99t7uD8M7OmgxR8grkXl2nURnDj9thR+9wUL+7PVVT4NefS+l/ZJoOLM8Oq+r0M1m2v70FH3PZwdQf+m54yldCCSoFM/iw9iFEN/WkCqf1zSsVTNAqVqryRhkbSV3QGitr5BoXBA2KZcbiZHv9JFITgp3khB+of+cJshoZykrB4NE/YqZpvEN3Kxu+YBjHt+zh+n4LCcwi2HCIpJLQiDJeyO7R0k4NuZPJ0EeRH8JxU99w58ghgmxXQi0TQYeFaseMdXZKic8xIzxfL1+4AyV7MRCoSHsTJB4bLx0yXRMx1CVboKKNO5ws1eSmnXhgNBCXyS5xU9cfUF1Nq7Irwuxby8="

before_install:
  - docker-compose -f docker-compose.yml up -d
script:
  - mvn clean install -DskipTests=true
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=RobbiNespu_ESS
after_success:
  # Generate test coverage report
  - mvn test
  # Install deepsource CLI
  - curl https://deepsource.io/cli | sh
  # From the root directory, run the report coverage command
  # This example is with respect to Gradle.
  # The report directory will be different for Maven.
  - ./bin/deepsource report --analyzer test-coverage --key java --value-file ./target/site/jacoco/jacoco.xml
  - bash <(curl -s https://codecov.io/bash)


