language: java
jdk:
  - oraclejdk11
before_install:
  - docker-compose -f docker-compose.yml up -d
script:
  - mvn clean install -DskipTests=true
after_success:
  # Generate test coverage report
  - mvn test

  # Install deepsource CLI
  - curl https://deepsource.io/cli | sh

  # From the root directory, run the report coverage command
  # This example is with respect to Gradle.
  # The report directory will be different for Maven.
  - ./bin/deepsource report --analyzer test-coverage --key java --value-file ./target/site/jacoco/jacoco.xml

